[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "openg2p-registry-cropsown-extension"
description = "OpenG2P Registry Crop Sown Extension"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MPL-2.0" }

authors = [
  { name = "OpenG2P", email = "info@openg2p.org" },
]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
  "Operating System :: OS Independent",
]

dependencies = [
  "openg2p-fastapi-common >=1.1.2",
  "openg2p-g2pconnect-common-lib >=1.1.0",
]

dynamic = ["version"]

[project.urls]
Homepage = "https://openg2p.org"
Documentation = "https://docs.openg2p.org/"
Repository = "https://github.com/OpenG2P/cropsown-registry"

[tool.hatch.version]
path = "src/openg2p_registry_cropsown_extension/__init__.py"
