import enum


class G2PRegistryErrorCodes(enum.Enum):

    # System Errors
    UNEXPECTED_ERROR = ("UNEXPECTED_ERROR", "SYS-ERR-001")

    # Request Validation Errors
    INVALID_REQUEST = ("INVALID_REQUEST", "REQ-VAL-000")
    REQUEST_VALIDATION_ERROR = ("REQUEST_VALIDATION_ERROR", "REQ-VAL-001")

    # Database Errors
    DATABASE_CONNECTION_ERROR = ("DATABASE_CONNECTION_ERROR", "DB-ERR-001")
    DATABASE_QUERY_ERROR = ("DATABASE_QUERY_ERROR", "DB-ERR-002")
    DATABASE_TRANSACTION_ERROR = ("DATABASE_TRANSACTION_ERROR", "DB-ERR-003")

    # Register Errors
    REGISTER_NOT_FOUND = ("REGISTER_NOT_FOUND", "REG-ERR-001")
    REGISTER_DATA_NOT_FOUND = ("REGISTER_DATA_NOT_FOUND", "REG-ERR-002")
    CHANGE_REQUEST_NOT_FOUND = ("CHANGE_REQUEST_NOT_FOUND", "REG-ERR-003")
    CHANGE_REQUEST_NOT_IN_PENDING_STATE = ("CHANGE_REQUEST_NOT_IN_PENDING_STATE", "REG-ERR-004")
    VERIFICATIONS_PENDING = ("VERIFICATIONS_PENDING", "REG-ERR-005")
    SECTION_NOT_FOUND = ("SECTION_NOT_FOUND", "REG-ERR-006")
    UNKNOWN_CHANGE_REQUEST_ACTION = ("UNKNOWN_CHANGE_REQUEST_ACTION", "REG-ERR-007")
    INTAKE_FORM_NOT_FOUND = ("INTAKE_FORM_NOT_FOUND", "REG-ERR-008")
    INTAKE_FORM_INVALID_STATE = ("INTAKE_FORM_INVALID_STATE", "REG-ERR-009")
    INTAKE_FORM_VERIFICATIONS_PENDING = ("INTAKE_FORM_VERIFICATIONS_PENDING", "REG-ERR-010")
    NON_CORE_SECTION_OPERATION_NOT_ALLOWED = ("NON_CORE_SECTION_OPERATION_NOT_ALLOWED", "REG-ERR-011")
    RECORD_ACCESS_DENIED = ("RECORD_ACCESS_DENIED", "REG-ERR-012")

    # Partner Errors
    PARTNER_NOT_REGISTERED = ("PARTNER_NOT_REGISTERED", "REGP-ERR-001")
    DATA_MODEL_NOT_FOUND = ("DATA_MODEL_NOT_FOUND", "REGP-ERR-002")

    # Ingestion Errors
    PARTNER_ALREADY_EXISTS = ("PARTNER_ALREADY_EXISTS", "ING-ERR-001")
    PARTNER_NOT_FOUND = ("PARTNER_NOT_FOUND", "ING-ERR-002")
    PATTERN_NOT_FOUND = ("PATTERN_NOT_FOUND", "ING-ERR-003")
    SEMANTIC_PATTERN_NOT_FOUND = ("SEMANTIC_PATTERN_NOT_FOUND", "ING-ERR-004")
    PAYLOAD_ENRICHER_NOT_FOUND = ("PAYLOAD_ENRICHER_NOT_FOUND", "ING-ERR-006")
    DATA_MODEL_ALREADY_EXISTS = ("DATA_MODEL_ALREADY_EXISTS", "ING-ERR-007")
    PATTERN_ALREADY_EXISTS_FOR_DATA_MODEL = (
        "PATTERN_ALREADY_EXISTS_FOR_DATA_MODEL",
        "ING-ERR-008",
    )
    PATTERN_ALREADY_EXISTS = ("PATTERN_ALREADY_EXISTS", "ING-ERR-008")

    # Outgestion Errors
    TOPIC_NOT_FOUND = ("TOPIC_NOT_FOUND", "OUT-ERR-001")
    TOPIC_ALREADY_EXISTS = ("TOPIC_ALREADY_EXISTS", "OUT-ERR-002")
    TOPIC_NOT_INACTIVE = ("TOPIC_NOT_INACTIVE", "OUT-ERR-003")

    # Template Errors
    TEMPLATE_NOT_FOUND = ("TEMPLATE_NOT_FOUND", "TPL-ERR-001")
    TEMPLATE_ALREADY_EXISTS = ("TEMPLATE_ALREADY_EXISTS", "TPL-ERR-002")

    # Document Errors
    DOCUMENT_NOT_FOUND = ("DOCUMENT_NOT_FOUND", "DOC-ERR-001")

    # File / document validation errors
    INVALID_FILE_NAME = ("INVALID_FILE_NAME", "DOC-VAL-001")
    INVALID_FILE_TYPE = ("INVALID_FILE_TYPE", "DOC-VAL-002")
    FILE_TOO_LARGE = ("FILE_TOO_LARGE", "DOC-VAL-003")
    INVALID_IMAGE_DIMENSIONS = ("INVALID_IMAGE_DIMENSIONS", "DOC-VAL-004")
    INVALID_FILE_CONTENT = ("INVALID_FILE_CONTENT", "DOC-VAL-005")

    # Subscription Errors
    SUBSCRIPTION_CALL_FAILED = ("SUBSCRIPTION_CALL_FAILED", "SUB-ERR-001")

    # Registry Configuration Errors
    REGISTRY_CONFIGURATION_NOT_FOUND = ("REGISTRY_CONFIGURATION_NOT_FOUND", "RCF-ERR-001")
    REGISTRY_CONFIGURATION_EXISTS = ("REGISTRY_CONFIGURATION_EXISTS", "RCF-ERR-002")
    REGISTRY_THEME_NOT_FOUND = ("REGISTRY_THEME_NOT_FOUND", "RTH-ERR-001")
    REGISTRY_THEME_EXISTS = ("REGISTRY_THEME_EXISTS", "RTH-ERR-002")
    FACTORY_THEME_DELETE_NOT_ALLOWED = ("FACTORY_THEME_DELETE_NOT_ALLOWED", "RTH-ERR-003")
    FACTORY_THEME_UPDATE_NOT_ALLOWED = ("FACTORY_THEME_UPDATE_NOT_ALLOWED", "RTH-ERR-004")
    REGISTRY_LANGUAGE_NOT_FOUND = ("REGISTRY_LANGUAGE_NOT_FOUND", "RLG-ERR-001")
    REGISTRY_LANGUAGE_EXISTS = ("REGISTRY_LANGUAGE_EXISTS", "RLG-ERR-002")

    # VC Config Errors
    VC_CONFIGURATION_NOT_FOUND = ("VC_CONFIGURATION_NOT_FOUND", "VCF-ERR-001")

    # Import file configuration errors
    IMPORT_FILE_CONFIGURATION_NOT_FOUND = ("IMPORT_FILE_CONFIGURATION_NOT_FOUND", "IF-ERR-001")
    
    # AWE policy configuration
    AWE_POLICY_CONFIGURATION_NOT_FOUND = ("AWE_POLICY_CONFIGURATION_NOT_FOUND", "AWE-ERR-001")
    AWE_WEBHOOK_SIGNATURE_INVALID = ("AWE_WEBHOOK_SIGNATURE_INVALID", "AWE-ERR-002")
    AWE_WEBHOOK_EVENT_ID_MISMATCH = ("AWE_WEBHOOK_EVENT_ID_MISMATCH", "AWE-ERR-003")
    AWE_WEBHOOK_REQUEST_MISMATCH = ("AWE_WEBHOOK_REQUEST_MISMATCH", "AWE-ERR-004")
    AWE_WEBHOOK_UNSUPPORTED_ARTIFACT = ("AWE_WEBHOOK_UNSUPPORTED_ARTIFACT", "AWE-ERR-005")
    AWE_REQUEST_FAILED = ("AWE_REQUEST_FAILED", "AWE-ERR-006")
    AWE_TASK_NOT_FOUND = ("AWE_TASK_NOT_FOUND", "AWE-ERR-007")
    AWE_BEARER_TOKEN_REQUIRED = ("AWE_BEARER_TOKEN_REQUIRED", "AWE-ERR-008")
    AWE_INVALID_STATE_TRANSITION = ("AWE_INVALID_STATE_TRANSITION", "AWE-007")

    # Score Computation Errors
    SCORE_DEFINITION_NOT_ALLOWED_FOR_REGISTER_PURPOSE = ("SCORE_DEFINITION_NOT_ALLOWED_FOR_REGISTER_PURPOSE", "SC-ERR-001")
    SCORE_DEFINITION_CONTRIBUTING_ATTRIBUTES_INVALID = ("SCORE_DEFINITION_CONTRIBUTING_ATTRIBUTES_INVALID", "SC-ERR-002")
    SCORE_DEFINITION_NOT_FOUND = ("SCORE_DEFINITION_NOT_FOUND", "SC-ERR-003")
    SCORE_NOT_FOUND = ("SCORE_NOT_FOUND", "SC-ERR-004")
    SCORE_COMPUTE_QUEUE_NOT_FOUND = ("SCORE_COMPUTE_QUEUE_NOT_FOUND", "SC-ERR-005")
    SCORE_COMPUTE_SERVICE_ERROR = ("SCORE_COMPUTE_SERVICE_ERROR", "SC-ERR-006")
    SCORE_VALIDATION_ERROR = ("SCORE_VALIDATION_ERROR", "SC-ERR-007")
    SCORE_CONTRIBUTING_ATTRIBUTE_NOT_FOUND = ("SCORE_CONTRIBUTING_ATTRIBUTE_NOT_FOUND", "SC-ERR-008")

    # Completion Score Errors
    COMPLETION_SCORE_NOT_FOUND = ("COMPLETION_SCORE_NOT_FOUND", "CMP-ERR-001")
    COMPLETION_SCORE_COMPUTE_FAILED = ("COMPLETION_SCORE_COMPUTE_FAILED", "CMP-ERR-002")
    COMPLETION_SCORE_QUEUE_ITEM_NOT_FOUND = ("COMPLETION_SCORE_QUEUE_ITEM_NOT_FOUND", "CMP-ERR-003")

    # Registrant Authentication Errors
    REGISTRANT_AUTH_PROVIDER_NOT_FOUND = ("REGISTRANT_AUTH_PROVIDER_NOT_FOUND", "RAU-ERR-002")
    REGISTRANT_AUTH_PROVIDER_INACTIVE = ("REGISTRANT_AUTH_PROVIDER_INACTIVE", "RAU-ERR-003")
    REGISTRANT_AUTH_PROVIDER_MISCONFIGURED = ("REGISTRANT_AUTH_PROVIDER_MISCONFIGURED", "RAU-ERR-004")
    REGISTRANT_AUTH_SESSION_INVALID_OR_EXPIRED = ("REGISTRANT_AUTH_SESSION_INVALID_OR_EXPIRED", "RAU-ERR-005")
    REGISTRANT_AUTH_RECORD_NOT_FOUND = ("REGISTRANT_AUTH_RECORD_NOT_FOUND", "RAU-ERR-006")
    REGISTRANT_AUTH_NOT_REQUIRED_FOR_REGISTER = ("REGISTRANT_AUTH_NOT_REQUIRED_FOR_REGISTER", "RAU-ERR-007")

    # Reference Data Errors
    ATTRIBUTE_NOT_FOUND = ("ATTRIBUTE_NOT_FOUND", "REF-ERR-001")
    ATTRIBUTE_ALREADY_EXISTS = ("ATTRIBUTE_ALREADY_EXISTS", "REF-ERR-002")
    ATTRIBUTE_HAS_VALUES = ("ATTRIBUTE_HAS_VALUES", "REF-ERR-003")
    ATTRIBUTE_HAS_HIERARCHICAL_VALUES = ("ATTRIBUTE_HAS_HIERARCHICAL_VALUES", "REF-ERR-004")
    ATTRIBUTE_VALUE_NOT_FOUND = ("ATTRIBUTE_VALUE_NOT_FOUND", "REF-ERR-005")
    ATTRIBUTE_VALUE_ALREADY_EXISTS = ("ATTRIBUTE_VALUE_ALREADY_EXISTS", "REF-ERR-006")
    ATTRIBUTE_VALUE_HAS_CHILDREN = ("ATTRIBUTE_VALUE_HAS_CHILDREN", "REF-ERR-007")

    # Keycloak Sync Errors
    KEYCLOAK_SYNC_ERROR = ("KEYCLOAK_SYNC_ERROR", "KCK-ERR-001")