import uuid
from datetime import datetime

from sqlalchemy import DateTime, Enum, String
from sqlalchemy.orm import Mapped, mapped_column
from openg2p_fastapi_common.models import BaseORMModel

from .enum import DocumentBucket


class G2PRegistryDocument(BaseORMModel):
    """
    Central catalog of uploaded documents. Every stored object (user documents,
    templates, record images, import files) has exactly one row here; all other
    tables reference documents by document_id.
    """
    __tablename__ = "g2p_registry_documents"

    document_id: Mapped[str] = mapped_column(
        String,
        primary_key=True,
        default=lambda: str(uuid.uuid4())
    )
    # Object key in the storage backend (uuid4().hex generated by the handler)
    document_store_id: Mapped[str] = mapped_column(
        String,
        nullable=False,
        index=True,
        unique=True
    )
    # Stored as VARCHAR; SQLAlchemy coerces to/from DocumentBucket StrEnum.
    bucket: Mapped[DocumentBucket] = mapped_column(
        Enum(
            DocumentBucket,
            name="document_bucket",
            native_enum=False,
            values_callable=lambda enum_cls: [member.value for member in enum_cls],
        ),
        nullable=False,
        index=True,
        default=DocumentBucket.DEFAULT,
    )
    source_filename: Mapped[str] = mapped_column(
        String,
        nullable=False
    )
    created_by: Mapped[str] = mapped_column(
        String,
        nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
        default=datetime.utcnow
    )
