-- Crop Sown Registry — sample crop sown records (local / demo only).
--
-- The platform db-seed's load_sample_data.py is shaped for the reference
-- (farmer) registry, so LOAD_SAMPLE_DATA stays false for this variant and this
-- sample set is applied explicitly instead (see docker-compose.yml).
--
-- Farmers are identified, not stored: each crop sown record carries the
-- farmer's ids and name, and mirrors the Fayda FAN into link_foundational_id.
--
-- Land is likewise not a register: a crop sown record covers exactly one plot,
-- whose attributes and geometry sit flat on the record. land_uuid is normally
-- generated by the ORM; these rows spell it out so the crop lines in
-- 20_crop_lines.sql can reference a known value.
--
-- Note cs0001 and cs0003 are the same farmer on two different plots: one record
-- per plot is what "land is flat on the record" means.

INSERT INTO "public"."g2p_register_crop_sowns" (
    "internal_record_id","functional_record_id","link_internal_record_id","link_foundational_id","record_name","record_image_document_id","created_by","created_at","last_approved_at","last_approved_by","search_text","record_status","record_status_reason","farmer_uuid","farmer_id","fayda_fan_id","farmer_name","farmer_odk_ack_id","status","production_year","lifecycle_stage","surveyor_name","surveyor_mobile_number","supervisor_name","supervisor_mobile_number","latitude","longitude","address_line_1","address_line_2","country_code"
) VALUES
('cs0001','REG/S1/2026/00001',NULL,'1234567890','Abebe Kebede',NULL,'seeder','2026-04-01 00:00:00','2026-04-01 00:00:00','seeder','REG/S1/2026/00001 Abebe Kebede FR-0000000001 1234567890 11111111-1111-4111-8111-111111111111 OR/01/02/003/00001 OWNER MEDIUM ANNUAL_CROP 2.5 HECTARE Gote 3 APPROVED 2026 PENDING_SOWING','ACTIVE',NULL,'a0000000-0000-4000-8000-000000000001','FR-0000000001','1234567890','Abebe Kebede','ODK-ACK-0001','APPROVAL_STATUS_APPROVED','2026','PENDING_SOWING','Chala Tesfaye','+251911000001','Muluken Assefa','+251911000002','9.0310','38.7420','Kebele 01','Gote 3','ETH'),
('cs0002','REG/S2/2026/00002',NULL,'9876543210','Almaz Tadesse',NULL,'seeder','2026-04-01 00:00:00','2026-04-01 00:00:00','seeder','REG/S2/2026/00002 Almaz Tadesse FR-0000000002 9876543210 33333333-3333-4333-8333-333333333333 AM/04/01/007/00011 OWNER HIGH ANNUAL_CROP 3.75 HECTARE Gote 1 APPROVED 2026 PENDING_HARVESTING','ACTIVE',NULL,'a0000000-0000-4000-8000-000000000002','FR-0000000002','9876543210','Almaz Tadesse','ODK-ACK-0002','APPROVAL_STATUS_APPROVED','2026','PENDING_HARVESTING','Chala Tesfaye','+251911000001','Muluken Assefa','+251911000002','8.5415','39.2712','Kebele 04','Gote 1','ETH'),
('cs0003','REG/S1/2026/00003',NULL,'1234567890','Abebe Kebede',NULL,'seeder','2026-04-01 00:00:00','2026-04-01 00:00:00','seeder','REG/S1/2026/00003 Abebe Kebede FR-0000000001 1234567890 22222222-2222-4222-8222-222222222222 OR/01/02/003/00002 TENANT LOW ANNUAL_CROP 1.0 HECTARE Gote 3 APPROVED 2026 PENDING_SOWING','ACTIVE',NULL,'a0000000-0000-4000-8000-000000000001','FR-0000000001','1234567890','Abebe Kebede','ODK-ACK-0003','APPROVAL_STATUS_APPROVED','2026','PENDING_SOWING','Chala Tesfaye','+251911000001','Muluken Assefa','+251911000002','9.0325','38.7455','Kebele 01','Gote 3','ETH')
ON CONFLICT ("internal_record_id") DO NOTHING;